### ISSUE TITLE
Clarify how to connect  ESP PCB pins with Ritto Wohntelefon 7360

### ISSUE THREAD

**Issue by Abdull** [Halfempty973/ritto-twinbus-esphome#1]
Great project!

Could you add documentation on how to connect the ESP PCB pins with the *Ritto Wohntelefon 7360* device?

In particular:

* what does H1 *Bell Sig* connect to?
* what does H1 *DO Pin (TO)* connect to?
  * *DO* as in *door open*?
  * *TO* as in *Tür offen*?
* what does H2 *GND (Twinbus)* connect to?
* is H2 *GND (PSU)* the power supply's ground?
* is H2 *Vin* the supply voltage provided by the power supply (*PSU*)?
  * is *Vin* supposed to be 5 V?
 
![image](https://github.com/user-attachments/assets/22f1c7d7-5606-45c9-afd2-484ffb590952)

Here is a photo of an opened *Ritto Wohntelefon 7360* (... */x0*), PCB revsion (?) *HW:15 7630.0.006.15* (photo released as public domain, [CC0](https://creativecommons.org/public-domain/cc0/)):

![ritto-twinbus-wohntelefon-7630-x0-pcb-front](https://github.com/user-attachments/assets/b4a81f24-c720-46fd-abb6-60b61172faf2)

**Comment by Halfempty973** [comment]
## I updated the repository to include 2 pictures, one for using the esphome pcb and one for using only the bare components

what does H1 Bell Sig connect to?
**Bell Sig connects to the middle pad out of the three on top**

what does H1 DO Pin (TO) connect to?
**DO (TO) connects to the third pin from the left side on the bottom pads. When this pin is pulled to ground the door lock will switch open**

DO as in door open?
TO as in Tür offen?
**Yes I wanted to include both the TO for "Türöffner" as well as DO for Door Opener**

what does H2 GND (Twinbus) connect to?
**With the pcb design you will need to connect the ground of the esphome pcb to the ground of the twinbus pcb, for that you can either use the left pad of the upper three or the fourth pad from the left on the bottom row**

is H2 GND (PSU) the power supply's ground?
**Yes it is, because I didn't want to connect two cables on one pad, because thats rather bulky**

is H2 Vin the supply voltage provided by the power supply (PSU)?
**Yes thats the supply voltage for the ESP8266 NodeMCU (input voltage can be between 4.5V - 10V on official NodeMCUs)
Keep in mind that a linear regulator regulates down the voltage so higher voltages will output more heat from the regulator**

is Vin supposed to be 5 V?
**In our build we used an old 5V power supply with a long cable connected to the VIN and GND**

**Comment by Abdull** [comment]
Awesome, thank you very much for providing the additional clarification and drawings. I'll give it a try using an [ESP32 board](https://esphome.io/components/esp32.html) ([`esp32doit-devkit-v1`](https://docs.platformio.org/en/latest/boards/espressif32/esp32doit-devkit-v1.html) in particular).

By the way: I noticed that the silkscreen next to the door opener tactile push button reads *TÖ* (versus *TO*; the umlaut dots are quite hidden). *TÖ* is also what the [latest *RITTO TwinBus System-Handbuch*](https://www.merten.de/fileadmin/import/files/ritto/technische_informationen/Ritto_System_Handbuch_2016.pdf) uses as the reference designator for *Türöffner*).

![image](https://github.com/user-attachments/assets/e1bf2f28-9194-4f11-a99f-52ca72376e7d)


I close this issue as I consider it resolved. Again, thank you very much for the fast response.
